import type { Metadata } from "next";
import { Prompt } from "next/font/google"
import "./globals.css";

const prompt = Prompt({weight: "300", subsets: ["latin", "thai"]})

export const metadata: Metadata = {
  title: "Facial Recognition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
